@php
    $input = 'mt-2 h-11 w-full rounded-xl border border-[#582308]/10 bg-[#faf7f0] px-4 text-sm text-[#32170b] outline-none transition focus:border-[#bd9150] focus:ring-2 focus:ring-[#bd9150]/15';
    $label = 'text-[10px] font-bold uppercase tracking-[.16em] text-[#32170b]/55';
@endphp

@if ($errors->any())
    <div class="mb-6 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-800"><p class="font-semibold">Periksa kembali data berikut:</p><ul class="mt-2 list-inside list-disc space-y-1 text-xs">@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>
@endif

<div class="grid gap-5 sm:grid-cols-2">
    <label class="block sm:col-span-2"><span class="{{ $label }}">Nama desain <b class="text-red-600">*</b></span><input class="{{ $input }}" name="name" value="{{ old('name', $catalog?->name) }}" maxlength="120" required>@error('name')<span class="mt-1 block text-xs text-red-600">{{ $message }}</span>@enderror</label>
    <label class="block sm:col-span-2"><span class="{{ $label }}">Link desain</span><input class="{{ $input }}" type="url" name="link" value="{{ old('link', $catalog?->link) }}" maxlength="2048" placeholder="https://contoh.com/desain"><span class="mt-1 block text-[10px] font-normal text-[#32170b]/40">Opsional. Jika diisi, seluruh kartu desain di katalog publik akan membuka link ini.</span>@error('link')<span class="mt-1 block text-xs text-red-600">{{ $message }}</span>@enderror</label>
    <label class="block"><span class="{{ $label }}">Kategori <b class="text-red-600">*</b></span><select class="{{ $input }}" name="category" required><option value="">Pilih kategori</option>@foreach ($categoryOptions as $category)<option value="{{ $category }}" @selected(old('category', $catalog?->category) === $category)>{{ $category }}</option>@endforeach</select><span class="mt-1 block text-[10px] font-normal text-[#32170b]/40">Kategori mengikuti data katalog dan Form Pesanan yang sudah tersedia.</span>@error('category')<span class="mt-1 block text-xs text-red-600">{{ $message }}</span>@enderror</label>
    <label class="block"><span class="{{ $label }}">Paket <b class="text-red-600">*</b></span><select class="{{ $input }}" name="package" required><option value="">Pilih paket</option>@foreach ($packageOptions as $package)<option value="{{ $package }}" @selected(old('package', $catalog?->package) === $package)>{{ $package }}</option>@endforeach</select><span class="mt-1 block text-[10px] font-normal text-[#32170b]/40">Pilihan otomatis mengikuti data pada menu Paket & Harga.</span>@error('package')<span class="mt-1 block text-xs text-red-600">{{ $message }}</span>@enderror</label>
    <label class="block"><span class="{{ $label }}">Warna desain <b class="text-red-600">*</b></span><div class="mt-2 flex h-11 items-center gap-3 rounded-xl border border-[#582308]/10 bg-[#faf7f0] px-3"><input class="size-7 cursor-pointer rounded border-0 bg-transparent p-0" type="color" name="color" value="{{ old('color', $catalog?->color ?? '#6b3520') }}" aria-label="Pilih warna desain" required><span class="text-xs text-[#32170b]/45">Pilih warna utama kartu</span></div>@error('color')<span class="mt-1 block text-xs text-red-600">{{ $message }}</span>@enderror</label>
    <label class="block"><span class="{{ $label }}">Gambar desain</span><input class="mt-2 block w-full rounded-xl border border-dashed border-[#582308]/20 bg-[#faf7f0] px-3 py-3 text-xs text-[#32170b]/55 file:mr-3 file:rounded-lg file:border-0 file:bg-[#582308] file:px-3 file:py-2 file:text-xs file:font-semibold file:text-white" type="file" name="image" accept="image/jpeg,image/png,image/webp">@if ($catalog?->image_path)<span class="mt-2 block text-[10px] text-[#32170b]/45">Gambar saat ini sudah tersimpan. Upload file baru untuk menggantinya.</span>@endif @error('image')<span class="mt-1 block text-xs text-red-600">{{ $message }}</span>@enderror</label>
    <label class="block"><span class="{{ $label }}">Status publikasi <b class="text-red-600">*</b></span><select class="{{ $input }}" name="status" required>@foreach (['active' => 'Aktif', 'draft' => 'Draft', 'archived' => 'Diarsipkan'] as $value => $text)<option value="{{ $value }}" @selected(old('status', $catalog?->status ?? 'draft') === $value)>{{ $text }}</option>@endforeach</select>@error('status')<span class="mt-1 block text-xs text-red-600">{{ $message }}</span>@enderror</label>
</div>

<div class="mt-8 flex flex-col-reverse gap-3 border-t border-[#582308]/8 pt-6 sm:flex-row sm:justify-end"><a href="{{ route('admin.catalog.index') }}" class="grid h-11 place-items-center rounded-xl border border-[#582308]/12 px-5 text-sm font-semibold text-[#582308]">Batal</a><button type="submit" class="h-11 rounded-xl bg-[#582308] px-6 text-sm font-semibold text-white"><i class="fa-solid fa-floppy-disk mr-2"></i>{{ $submitLabel }}</button></div>
