<!DOCTYPE html>
<html lang="id">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Pembayaran Memoire"><title>Pembayaran — Memoire Admin</title>@vite('resources/css/app.css')</head>
<body class="bg-[#f4efe7] text-[#32170b] antialiased">
@php
    $statusLabels = ['pending' => 'Menunggu', 'success' => 'Berhasil', 'paid' => 'Lunas', 'failed' => 'Gagal', 'expired' => 'Kedaluwarsa', 'cancelled' => 'Dibatalkan', 'refunded' => 'Dikembalikan'];
    $statusClasses = ['pending' => 'bg-amber-50 text-amber-700', 'success' => 'bg-emerald-50 text-emerald-700', 'paid' => 'bg-emerald-50 text-emerald-700', 'failed' => 'bg-red-50 text-red-700', 'expired' => 'bg-stone-100 text-stone-600', 'cancelled' => 'bg-stone-100 text-stone-600', 'refunded' => 'bg-stone-100 text-stone-600'];
    $methodIcons = ['bca' => 'fa-building-columns', 'dana' => 'fa-wallet', 'gopay' => 'fa-mobile-screen-button'];
@endphp
<div class="min-h-screen lg:grid lg:grid-cols-[17rem_1fr]">
    @include('admin.partials.sidebar')
    <main class="min-w-0">
        <header class="sticky top-0 z-30 flex min-h-20 items-center justify-between gap-3 border-b border-[#582308]/10 bg-[#f4efe7]/90 px-5 py-3 backdrop-blur-xl sm:px-8 lg:min-h-24 lg:px-10">
            <div><p class="text-xs text-[#32170b]/45">Kelola transaksi</p><h1 class="mt-1 font-display text-2xl text-[#582308] sm:text-3xl">Pembayaran</h1></div>
            <div class="flex gap-2"><a href="{{ route('admin.payments.export', request()->query()) }}" class="grid size-11 place-items-center rounded-full border border-[#582308]/12 bg-white text-[#582308] sm:flex sm:w-auto sm:gap-2 sm:px-5"><i class="fa-solid fa-file-export text-xs"></i><span class="hidden text-sm font-semibold sm:inline">Ekspor</span></a><a href="{{ route('admin.payments.create') }}" class="flex h-11 items-center gap-2 rounded-full bg-[#582308] px-4 text-xs font-semibold text-white sm:px-5 sm:text-sm"><i class="fa-solid fa-plus"></i><span class="hidden sm:inline">Tambah transaksi</span></a></div>
        </header>
        <div class="space-y-6 p-5 sm:p-8 lg:p-10">
            @if(session('success'))<p role="status" class="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800">{{ session('success') }}</p>@endif
            @if(session('error'))<p role="alert" class="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800">{{ session('error') }}</p>@endif

            <section class="grid grid-cols-2 gap-3 xl:grid-cols-4" aria-label="Ringkasan pembayaran">
                @foreach ([
                    ['Rp '.number_format((float) $summary['month_revenue'], 0, ',', '.'), 'Pendapatan bulan ini', now()->translatedFormat('F Y'), 'fa-chart-line'],
                    ['Rp '.number_format((float) $summary['week_revenue'], 0, ',', '.'), 'Dana minggu ini', $summary['week_transactions'].' transaksi', 'fa-wallet'],
                    [$summary['pending'], 'Menunggu pembayaran', 'Perlu ditinjau', 'fa-clock'],
                    ['Rp '.number_format((float) $summary['refunded'], 0, ',', '.'), 'Dana dikembalikan', $summary['refund_transactions'].' transaksi', 'fa-rotate-left'],
                ] as [$value, $label, $note, $icon])
                    <article class="rounded-2xl border border-[#582308]/8 bg-white p-4 shadow-[0_8px_25px_rgba(88,35,8,.035)] sm:p-5"><div class="flex items-start justify-between gap-3"><span class="grid size-10 place-items-center rounded-xl bg-[#ead5ac]/45 text-[#582308]"><i class="fa-solid {{ $icon }} text-sm"></i></span><span class="text-right text-[9px] font-semibold text-[#32170b]/35">{{ $note }}</span></div><p class="mt-5 font-display text-xl text-[#582308] sm:text-3xl">{{ $value }}</p><p class="mt-1 text-[10px] text-[#32170b]/45 sm:text-xs">{{ $label }}</p></article>
                @endforeach
            </section>

            <div class="grid gap-6 xl:grid-cols-[1.7fr_.8fr]">
                <section class="rounded-3xl border border-[#582308]/8 bg-white p-5 shadow-[0_10px_35px_rgba(88,35,8,.04)] sm:p-6"><div class="flex items-start justify-between gap-4"><div><h2 class="font-display text-xl text-[#582308]">Arus pendapatan</h2><p class="mt-1 text-xs text-[#32170b]/40">Transaksi berhasil berdasarkan periode</p></div><form method="GET"><input type="hidden" name="search" value="{{ $filters['search'] ?? '' }}"><input type="hidden" name="status" value="{{ $filters['status'] ?? '' }}"><input type="hidden" name="payment_method_id" value="{{ $filters['payment_method_id'] ?? '' }}"><select name="period" onchange="this.form.submit()" aria-label="Periode grafik" class="rounded-xl border border-[#582308]/10 bg-[#faf7f0] px-3 py-2 text-[10px] text-[#32170b]/60 outline-none"><option value="6" @selected(($filters['period'] ?? 6) == 6)>6 bulan</option><option value="12" @selected(($filters['period'] ?? 6) == 12)>12 bulan</option></select></form></div><div class="mt-8 flex h-48 items-end gap-2 border-b border-[#582308]/10 sm:gap-4" aria-label="Grafik pendapatan bulanan">@foreach($chart as $item)<div class="group flex h-full flex-1 flex-col justify-end gap-2 text-center"><span class="text-[8px] font-semibold text-[#582308] opacity-0 transition group-hover:opacity-100">Rp {{ number_format($item['amount'], 0, ',', '.') }}</span><div class="mx-auto w-full max-w-12 rounded-t-xl {{ $loop->last ? 'bg-[#582308]' : 'bg-[#ead5ac]' }}" style="height: {{ $item['percentage'] }}%"></div><span class="pb-3 text-[8px] text-[#32170b]/40 sm:text-[9px]">{{ $item['label'] }}</span></div>@endforeach</div></section>
                <section class="relative overflow-hidden rounded-3xl bg-[#582308] p-6 text-white shadow-[0_20px_50px_rgba(88,35,8,.16)]"><div class="absolute -right-12 -top-12 size-40 rounded-full border border-[#ead5ac]/15"></div><span class="grid size-11 place-items-center rounded-xl bg-[#ead5ac] text-[#582308]"><i class="fa-solid fa-building-columns"></i></span><p class="mt-8 text-[9px] font-bold uppercase tracking-[.22em] text-[#ead5ac]/70">Saldo tersedia</p><p class="mt-2 font-display text-3xl text-[#ead5ac]">Rp {{ number_format((float) $summary['available_balance'], 0, ',', '.') }}</p><p class="mt-2 text-xs leading-6 text-white/45">Dihitung dari transaksi berhasil dikurangi pengembalian dana.</p><div class="mt-7 border-t border-white/10 pt-5"><div class="flex items-center justify-between gap-3 text-xs"><span class="text-white/45">Metode utama</span><span class="truncate font-semibold">{{ $primaryPaymentMethod?->name ?? 'Belum tersedia' }}</span></div>@if($primaryPaymentMethod)<a href="{{ route('admin.payment-methods.edit', $primaryPaymentMethod) }}" class="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-[#ead5ac] py-3 text-xs font-semibold text-[#582308]"><i class="fa-solid fa-pen"></i>Kelola pencairan</a>@endif</div></section>
            </div>

            <section class="rounded-3xl border border-[#582308]/8 bg-white p-5 shadow-[0_10px_35px_rgba(88,35,8,.04)] sm:p-6">
                <div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 class="font-display text-xl text-[#582308]">Metode pembayaran</h2><p class="mt-1 text-xs text-[#32170b]/40">BCA, DANA, dan GoPay dapat diedit sesuai akun bisnis Anda.</p></div><a href="{{ route('admin.payment-methods.create') }}" class="inline-flex h-10 items-center justify-center gap-2 rounded-xl border border-[#582308]/12 px-4 text-xs font-semibold text-[#582308]"><i class="fa-solid fa-plus"></i>Tambah metode</a></div>
                <div class="mt-5 grid gap-4 md:grid-cols-3">@foreach($paymentMethods as $method)<article class="rounded-2xl border border-[#582308]/10 bg-[#faf7f0] p-5"><div class="flex items-start justify-between"><span class="grid size-10 place-items-center rounded-xl bg-[#ead5ac]/55 text-[#582308]"><i class="fa-solid {{ $methodIcons[$method->code] ?? 'fa-wallet' }}"></i></span><span class="rounded-full px-2.5 py-1 text-[9px] font-bold {{ $method->is_active ? 'bg-emerald-50 text-emerald-700' : 'bg-stone-200 text-stone-600' }}">{{ $method->is_active ? 'Aktif' : 'Nonaktif' }}</span></div><h3 class="mt-4 font-display text-xl text-[#582308]">{{ $method->name }}</h3><p class="mt-1 text-xs text-[#32170b]/50">{{ $method->account_name }}</p><p class="mt-2 font-semibold tracking-wide text-[#582308]">{{ $method->account_number }}</p><p class="mt-3 text-[10px] text-[#32170b]/40">{{ $method->payments_count }} transaksi</p><div class="mt-4 flex gap-2 border-t border-[#582308]/8 pt-4"><a href="{{ route('admin.payment-methods.edit', $method) }}" class="rounded-lg bg-white px-3 py-2 text-xs font-semibold text-[#582308]">Edit</a><form method="POST" action="{{ route('admin.payment-methods.destroy', $method) }}" onsubmit="return confirm('Hapus metode {{ $method->name }}?')">@csrf @method('DELETE')<button class="rounded-lg px-3 py-2 text-xs text-red-700">Hapus</button></form></div></article>@endforeach</div>
            </section>

            <section class="overflow-hidden rounded-3xl border border-[#582308]/8 bg-white shadow-[0_10px_35px_rgba(88,35,8,.04)]">
                <div class="flex flex-col gap-4 border-b border-[#582308]/8 p-5 sm:p-6 xl:flex-row xl:items-end xl:justify-between"><div><h2 class="font-display text-xl text-[#582308]">Riwayat transaksi</h2><p class="mt-1 text-xs text-[#32170b]/40">Pantau seluruh pembayaran pesanan</p></div><form method="GET" action="{{ route('admin.payments.index') }}" class="grid gap-2 sm:grid-cols-3"><label class="relative block"><span class="pointer-events-none absolute inset-y-0 left-0 grid w-10 place-items-center text-[#32170b]/30"><i class="fa-solid fa-magnifying-glass text-xs"></i></span><input name="search" value="{{ $filters['search'] ?? '' }}" type="search" placeholder="Cari transaksi..." class="h-10 w-full rounded-xl border border-[#582308]/10 bg-[#faf7f0] pl-10 pr-4 text-xs outline-none"></label><select name="status" class="h-10 rounded-xl border border-[#582308]/10 bg-[#faf7f0] px-3 text-xs"><option value="">Semua status</option>@foreach($statusLabels as $value => $label)<option value="{{ $value }}" @selected(($filters['status'] ?? '') === $value)>{{ $label }}</option>@endforeach</select><div class="flex gap-2"><select name="payment_method_id" class="h-10 min-w-32 rounded-xl border border-[#582308]/10 bg-[#faf7f0] px-3 text-xs"><option value="">Semua metode</option>@foreach($activePaymentMethods as $method)<option value="{{ $method->id }}" @selected((string) ($filters['payment_method_id'] ?? '') === (string) $method->id)>{{ $method->name }}</option>@endforeach</select><button class="grid size-10 place-items-center rounded-xl bg-[#582308] text-white" aria-label="Terapkan filter"><i class="fa-solid fa-filter text-xs"></i></button></div></form></div>
                <div class="overflow-x-auto"><table class="w-full min-w-[900px] text-left"><thead><tr class="border-b border-[#582308]/7 bg-[#faf7f0] text-[9px] uppercase tracking-[.16em] text-[#32170b]/40"><th class="px-6 py-4">Transaksi</th><th class="px-3 py-4">Pelanggan</th><th class="px-3 py-4">Metode</th><th class="px-3 py-4">Tanggal</th><th class="px-3 py-4">Nominal</th><th class="px-3 py-4">Status</th><th class="px-6 py-4"></th></tr></thead><tbody class="divide-y divide-[#582308]/7">@forelse($payments as $payment)<tr class="text-sm hover:bg-[#faf7f0]/75"><td class="px-6 py-4"><p class="text-xs font-semibold text-[#582308]">{{ $payment->transaction_number }}</p><p class="mt-1 text-[10px] text-[#32170b]/35">{{ $payment->order->order_number }}</p></td><td class="px-3 py-4 text-xs font-semibold">{{ $payment->order->customer_name }}</td><td class="px-3 py-4 text-xs text-[#32170b]/55"><i class="fa-solid {{ $methodIcons[$payment->paymentMethod->code] ?? 'fa-wallet' }} mr-2 text-[#bd9150]"></i>{{ $payment->paymentMethod->name }}</td><td class="px-3 py-4 text-xs text-[#32170b]/45">{{ ($payment->paid_at ?? $payment->created_at)->translatedFormat('d M Y · H.i') }}</td><td class="px-3 py-4 text-xs font-semibold text-[#582308]">Rp {{ number_format((float) $payment->amount, 0, ',', '.') }}</td><td class="px-3 py-4"><span class="inline-flex items-center gap-2 rounded-full px-3 py-1.5 text-[10px] font-semibold {{ $statusClasses[$payment->status] }}"><span class="size-1.5 rounded-full bg-current"></span>{{ $statusLabels[$payment->status] }}</span></td><td class="px-6 py-4"><div class="flex justify-end gap-1"><a href="{{ route('admin.payments.show', $payment) }}" class="grid size-8 place-items-center rounded-lg text-[#32170b]/35 hover:bg-[#ead5ac]/40" aria-label="Lihat detail {{ $payment->transaction_number }}"><i class="fa-regular fa-eye"></i></a><a href="{{ route('admin.payments.edit', $payment) }}" class="grid size-8 place-items-center rounded-lg text-[#32170b]/35 hover:bg-[#ead5ac]/40" aria-label="Edit {{ $payment->transaction_number }}"><i class="fa-solid fa-pen"></i></a><form method="POST" action="{{ route('admin.payments.destroy', $payment) }}" onsubmit="return confirm('Hapus transaksi {{ $payment->transaction_number }}?')">@csrf @method('DELETE')<button class="grid size-8 place-items-center rounded-lg text-red-600/60 hover:bg-red-50" aria-label="Hapus {{ $payment->transaction_number }}"><i class="fa-regular fa-trash-can"></i></button></form></div></td></tr>@empty<tr><td colspan="7" class="px-6 py-16 text-center"><p class="font-display text-xl text-[#582308]">Belum ada transaksi</p><p class="mt-2 text-xs text-[#32170b]/45">Tambahkan pembayaran pertama atau ubah filter pencarian.</p></td></tr>@endforelse</tbody></table></div>
                <div class="flex flex-col items-center justify-between gap-4 border-t border-[#582308]/8 px-6 py-4 sm:flex-row"><p class="text-[10px] text-[#32170b]/40">Menampilkan {{ $payments->firstItem() ?? 0 }}-{{ $payments->lastItem() ?? 0 }} dari {{ $payments->total() }} transaksi</p>{{ $payments->links() }}</div>
            </section>
        </div>
    </main>
</div>
</body></html>
