<!DOCTYPE html>
<html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{{ $order->order_number }} — Memoire Admin</title>@vite('resources/css/app.css')</head>
<body class="bg-[#f4efe7] text-[#32170b] antialiased">
    @php($statusLabels = ['waiting' => 'Menunggu data', 'process' => 'Dalam proses', 'revision' => 'Revisi', 'ready' => 'Siap dikirim', 'done' => 'Selesai', 'cancelled' => 'Dibatalkan'])
    @php($paymentLabels = ['unpaid' => 'Belum lunas', 'paid' => 'Lunas', 'refunded' => 'Dikembalikan'])
    <div class="min-h-screen lg:grid lg:grid-cols-[17rem_1fr]">@include('admin.partials.sidebar')<main class="min-w-0">
        <header class="sticky top-0 z-30 flex h-20 items-center justify-between border-b border-[#582308]/10 bg-[#f4efe7]/90 px-5 backdrop-blur-xl sm:px-8 lg:h-24 lg:px-10"><div><a href="{{ route('admin.orders.index') }}" class="text-xs text-[#32170b]/45"><i class="fa-solid fa-arrow-left mr-2"></i>Semua pesanan</a><h1 class="mt-2 font-display text-2xl text-[#582308] sm:text-3xl">{{ $order->order_number }}</h1></div><a href="{{ route('admin.orders.edit', $order) }}" class="flex h-11 items-center gap-2 rounded-full bg-[#582308] px-5 text-sm font-semibold text-white"><i class="fa-solid fa-pen text-xs"></i><span class="hidden sm:inline">Edit Pesanan</span></a></header>
        <div class="space-y-6 p-5 sm:p-8 lg:p-10">
            @if (session('success'))<div class="flex items-center gap-3 rounded-2xl border border-emerald-200 bg-emerald-50 px-5 py-4 text-sm text-emerald-800"><i class="fa-solid fa-circle-check"></i>{{ session('success') }}</div>@endif
            <div class="grid gap-6 xl:grid-cols-[1.5fr_.7fr]">
                <section class="rounded-3xl border border-[#582308]/8 bg-white p-6 shadow-[0_10px_35px_rgba(88,35,8,.04)] sm:p-8"><div class="flex flex-col gap-4 border-b border-[#582308]/8 pb-6 sm:flex-row sm:items-center sm:justify-between"><div><p class="text-[10px] font-bold uppercase tracking-[.18em] text-[#32170b]/40">Pelanggan</p><h2 class="mt-2 font-display text-3xl text-[#582308]">{{ $order->customer_name }}</h2></div><span class="admin-status admin-status-{{ $order->status }} w-fit"><span></span>{{ $statusLabels[$order->status] }}</span></div>
                    <dl class="mt-6 grid gap-x-8 gap-y-6 sm:grid-cols-2">@foreach ([['Email', $order->email], ['WhatsApp', $order->phone ?: 'Belum diisi'], ['Paket', $order->package], ['Jenis acara', $order->event_type], ['Tanggal acara', $order->event_date?->translatedFormat('d F Y') ?? 'Belum ditentukan'], ['Dibuat', $order->created_at->translatedFormat('d F Y, H.i')]] as [$term, $value])<div><dt class="text-[9px] font-bold uppercase tracking-[.16em] text-[#32170b]/35">{{ $term }}</dt><dd class="mt-2 text-sm font-medium text-[#32170b]/75">{{ $value }}</dd></div>@endforeach</dl>
                    <div class="mt-8 rounded-2xl bg-[#faf7f0] p-5"><p class="text-[9px] font-bold uppercase tracking-[.16em] text-[#32170b]/35">Catatan</p><p class="mt-3 whitespace-pre-line text-sm leading-7 text-[#32170b]/60">{{ $order->notes ?: 'Tidak ada catatan untuk pesanan ini.' }}</p></div>
                    @if ($order->form_data)<div class="mt-5 rounded-2xl border border-[#582308]/10 bg-white p-5"><p class="text-[9px] font-bold uppercase tracking-[.16em] text-[#32170b]/35">Data formulir {{ $order->form_category }}</p><dl class="mt-4 grid gap-4 sm:grid-cols-2">@foreach ($order->form_data as $label => $value)<div><dt class="text-xs font-semibold text-[#582308]">{{ str($label)->replace('_', ' ')->title() }}</dt><dd class="mt-1 whitespace-pre-line text-sm text-[#32170b]/60">{{ $value ?: '—' }}</dd></div>@endforeach</dl></div>@endif
                </section>
                <aside class="space-y-5"><section class="rounded-3xl bg-[#582308] p-6 text-white shadow-[0_20px_50px_rgba(88,35,8,.16)]"><p class="text-[9px] font-bold uppercase tracking-[.2em] text-[#ead5ac]/70">Nilai pesanan</p><p class="mt-3 font-display text-3xl text-[#ead5ac]">Rp {{ number_format((float) $order->total, 0, ',', '.') }}</p><div class="mt-6 flex items-center justify-between border-t border-white/10 pt-5 text-xs"><span class="text-white/45">Pembayaran</span><span class="font-semibold text-[#ead5ac]">{{ $paymentLabels[$order->payment_status] }}</span></div></section><section class="rounded-3xl border border-red-100 bg-white p-6"><p class="font-display text-lg text-[#582308]">Hapus pesanan</p><p class="mt-2 text-xs leading-6 text-[#32170b]/45">Data yang dihapus tidak dapat dikembalikan.</p><form class="mt-5" action="{{ route('admin.orders.destroy', $order) }}" method="POST" onsubmit="return confirm('Yakin ingin menghapus pesanan ini?')">@csrf @method('DELETE')<button class="w-full rounded-xl border border-red-200 py-3 text-xs font-semibold text-red-700 hover:bg-red-50"><i class="fa-regular fa-trash-can mr-2"></i>Hapus Pesanan</button></form></section></aside>
            </div>
        </div>
    </main></div>
</body></html>
