@php
    $input = 'mt-2 h-11 w-full rounded-xl border border-[#582308]/10 bg-[#faf7f0] px-4 text-sm text-[#32170b] outline-none focus:border-[#bd9150] focus:ring-2 focus:ring-[#bd9150]/15';
    $label = 'text-[10px] font-bold uppercase tracking-[.16em] text-[#32170b]/55';
@endphp
@if($errors->any())<div class="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-800"><ul class="list-inside list-disc space-y-1">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="grid gap-5 sm:grid-cols-2">
    <label><span class="{{ $label }}">Jenis metode <b class="text-red-600">*</b></span><select class="{{ $input }}" name="code" required><option value="">Pilih metode</option>@foreach(['bca' => 'Transfer Bank BCA', 'dana' => 'DANA', 'gopay' => 'GoPay'] as $value => $text)<option value="{{ $value }}" @selected(old('code', $paymentMethod?->code) === $value)>{{ $text }}</option>@endforeach</select>@error('code')<span class="mt-1 block text-xs text-red-600">{{ $message }}</span>@enderror</label>
    <label><span class="{{ $label }}">Nama tampilan <b class="text-red-600">*</b></span><input class="{{ $input }}" name="name" maxlength="80" value="{{ old('name', $paymentMethod?->name) }}" required>@error('name')<span class="mt-1 block text-xs text-red-600">{{ $message }}</span>@enderror</label>
    <label><span class="{{ $label }}">Nama pemilik akun <b class="text-red-600">*</b></span><input class="{{ $input }}" name="account_name" maxlength="120" value="{{ old('account_name', $paymentMethod?->account_name) }}" required>@error('account_name')<span class="mt-1 block text-xs text-red-600">{{ $message }}</span>@enderror</label>
    <label><span class="{{ $label }}">Nomor rekening/akun <b class="text-red-600">*</b></span><input class="{{ $input }}" name="account_number" maxlength="80" value="{{ old('account_number', $paymentMethod?->account_number) }}" required>@error('account_number')<span class="mt-1 block text-xs text-red-600">{{ $message }}</span>@enderror</label>
    <label><span class="{{ $label }}">Nomor urut <b class="text-red-600">*</b></span><input class="{{ $input }}" type="number" name="sort_order" min="0" max="999" value="{{ old('sort_order', $paymentMethod?->sort_order ?? 0) }}" required>@error('sort_order')<span class="mt-1 block text-xs text-red-600">{{ $message }}</span>@enderror</label>
    <label class="flex items-end gap-3 pb-3 text-sm font-semibold text-[#582308]"><input type="hidden" name="is_active" value="0"><input type="checkbox" name="is_active" value="1" @checked(old('is_active', $paymentMethod?->is_active ?? true))>Metode aktif</label>
    <label class="sm:col-span-2"><span class="{{ $label }}">Instruksi pembayaran</span><textarea class="mt-2 min-h-28 w-full rounded-xl border border-[#582308]/10 bg-[#faf7f0] px-4 py-3 text-sm outline-none focus:border-[#bd9150]" name="instructions" maxlength="1000">{{ old('instructions', $paymentMethod?->instructions) }}</textarea>@error('instructions')<span class="mt-1 block text-xs text-red-600">{{ $message }}</span>@enderror</label>
</div>
<div class="mt-8 flex flex-col-reverse gap-3 border-t border-[#582308]/8 pt-6 sm:flex-row sm:justify-end"><a href="{{ route('admin.payments.index') }}" class="grid h-11 place-items-center rounded-xl border border-[#582308]/12 px-5 text-sm font-semibold text-[#582308]">Batal</a><button class="h-11 rounded-xl bg-[#582308] px-6 text-sm font-semibold text-white"><i class="fa-solid fa-floppy-disk mr-2"></i>{{ $submitLabel }}</button></div>
