<!DOCTYPE html>
<html lang="id">
    <head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{{ $conversation->ticket_number }} — Live Chat Memoire</title>@vite('resources/css/app.css')</head>
    <body class="bg-[#f4efe7] text-[#32170b] antialiased">
        <div class="min-h-screen lg:grid lg:grid-cols-[17rem_1fr]">@include('admin.partials.sidebar')<main class="min-w-0">
            <header class="sticky top-0 z-30 flex h-20 items-center justify-between border-b border-[#582308]/10 bg-[#f4efe7]/90 px-5 backdrop-blur-xl sm:px-8 lg:h-24 lg:px-10"><div><a href="{{ route('admin.chats.index') }}" class="text-xs text-[#32170b]/45"><i class="fa-solid fa-arrow-left mr-2"></i>Kembali ke Live Chat</a><h1 class="mt-2 font-display text-2xl text-[#582308]">{{ $conversation->guest_name }}</h1></div><div class="flex items-center gap-2"><form action="{{ route('admin.chats.status', $conversation) }}" method="POST">@csrf @method('PATCH')<select name="status" onchange="this.form.submit()" class="rounded-xl border border-[#582308]/10 bg-white px-3 py-2 text-xs font-semibold text-[#582308] outline-none"><option value="waiting" @selected($conversation->status === 'waiting')>Menunggu</option><option value="active" @selected($conversation->status === 'active')>Aktif</option><option value="closed" @selected($conversation->status === 'closed')>Tutup tiket</option></select></form>@if ($conversation->status !== 'closed')<form action="{{ route('admin.chats.status', $conversation) }}" method="POST" onsubmit="return confirm('Akhiri chat ini?')">@csrf @method('PATCH')<input type="hidden" name="status" value="closed"><button class="rounded-xl border border-red-200 bg-white px-3 py-2 text-xs font-semibold text-red-700 hover:bg-red-50"><i class="fa-solid fa-check mr-1"></i>Akhiri Chat</button></form>@endif</div></header>
            <div class="mx-auto grid max-w-6xl gap-6 p-5 sm:p-8 xl:grid-cols-[1fr_17rem] xl:p-10"><section class="flex min-h-[38rem] flex-col overflow-hidden rounded-3xl border border-[#582308]/8 bg-white shadow-[0_10px_35px_rgba(88,35,8,.04)]"><div class="border-b border-[#582308]/8 px-6 py-4"><p class="text-[9px] font-bold uppercase tracking-[.2em] text-[#32170b]/40">Tiket {{ $conversation->ticket_number }}</p><p class="mt-1 text-xs text-[#32170b]/55">{{ $conversation->guest_phone ?: 'Nomor WhatsApp tidak diberikan' }}</p></div><div class="flex-1 space-y-4 overflow-y-auto bg-[#faf7f0]/60 p-5">@foreach ($conversation->messages as $message)<div class="flex {{ $message->sender_type === 'admin' ? 'justify-end' : 'justify-start' }}"><div class="max-w-[82%] rounded-2xl px-4 py-3 text-sm leading-6 {{ $message->sender_type === 'admin' ? 'rounded-br-md bg-[#582308] text-white' : 'rounded-bl-md bg-white text-[#32170b] shadow-sm' }}"><p>{{ $message->message }}</p><p class="mt-1 text-right text-[9px] {{ $message->sender_type === 'admin' ? 'text-white/45' : 'text-[#32170b]/35' }}">{{ $message->created_at->format('H.i') }}</p></div></div>@endforeach</div><form action="{{ route('admin.chats.reply', $conversation) }}" method="POST" class="border-t border-[#582308]/8 p-4">@csrf @error('message')<p class="mb-2 text-xs text-red-600">{{ $message }}</p>@enderror<div class="flex gap-3"><textarea name="message" required maxlength="1000" rows="2" placeholder="Tulis balasan untuk {{ $conversation->guest_name }}..." class="min-h-12 flex-1 resize-none rounded-xl border border-[#582308]/10 bg-[#faf7f0] px-4 py-3 text-sm outline-none focus:border-[#bd9150]"></textarea><button class="grid size-12 place-items-center self-end rounded-xl bg-[#582308] text-white" aria-label="Kirim balasan"><i class="fa-solid fa-paper-plane"></i></button></div></form></section><aside class="space-y-4"><section class="rounded-3xl bg-[#582308] p-6 text-white"><p class="text-[9px] font-bold uppercase tracking-[.2em] text-[#ead5ac]/70">Status tiket</p><p class="mt-3 font-display text-2xl text-[#ead5ac]">{{ ucfirst($conversation->status) }}</p><p class="mt-3 text-xs leading-6 text-white/45">Dibuat {{ $conversation->created_at->diffForHumans() }}</p></section><section class="rounded-3xl border border-[#582308]/8 bg-white p-6"><p class="text-[9px] font-bold uppercase tracking-[.2em] text-[#32170b]/35">Data pengunjung</p><p class="mt-4 font-display text-xl text-[#582308]">{{ $conversation->guest_name }}</p><p class="mt-2 text-xs text-[#32170b]/50">{{ $conversation->guest_phone ?: 'Tidak ada WhatsApp' }}</p></section></aside></div>
        </main></div>
    </body>
</html>
