@php
    $input = 'mt-2 h-11 w-full rounded-xl border border-[#582308]/10 bg-[#faf7f0] px-4 text-sm text-[#32170b] outline-none transition focus:border-[#bd9150] focus:ring-2 focus:ring-[#bd9150]/15';
    $label = 'text-[10px] font-bold uppercase tracking-[.16em] text-[#32170b]/55';
@endphp
@if($errors->any())<div class="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-800"><p class="font-semibold">Periksa kembali data berikut:</p><ul class="mt-2 list-inside list-disc space-y-1 text-xs">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="grid gap-5 sm:grid-cols-2">
    <label class="block sm:col-span-2"><span class="{{ $label }}">Pesanan <b class="text-red-600">*</b></span><select class="{{ $input }}" name="order_id" required><option value="">Pilih pesanan</option>@foreach($orders as $order)<option value="{{ $order->id }}" @selected((string) old('order_id', $payment?->order_id) === (string) $order->id)>{{ $order->order_number }} — {{ $order->customer_name }} (Rp {{ number_format((float) $order->total, 0, ',', '.') }})</option>@endforeach</select>@error('order_id')<span class="mt-1 block text-xs text-red-600">{{ $message }}</span>@enderror</label>
    <label class="block"><span class="{{ $label }}">Nomor transaksi</span><input class="{{ $input }}" name="transaction_number" value="{{ old('transaction_number', $payment?->transaction_number) }}" placeholder="Otomatis jika dikosongkan" maxlength="30">@error('transaction_number')<span class="mt-1 block text-xs text-red-600">{{ $message }}</span>@enderror</label>
    <label class="block"><span class="{{ $label }}">Metode pembayaran <b class="text-red-600">*</b></span><select class="{{ $input }}" name="payment_method_id" required><option value="">Pilih metode</option>@foreach($paymentMethods as $method)<option value="{{ $method->id }}" @selected((string) old('payment_method_id', $payment?->payment_method_id) === (string) $method->id)>{{ $method->name }} — {{ $method->account_number }}</option>@endforeach</select>@error('payment_method_id')<span class="mt-1 block text-xs text-red-600">{{ $message }}</span>@enderror</label>
    <label class="block"><span class="{{ $label }}">Nominal <b class="text-red-600">*</b></span><div class="relative"><span class="absolute inset-y-2 left-4 flex items-center text-sm text-[#32170b]/40">Rp</span><input class="{{ $input }} pl-11" type="number" name="amount" min="0" step="1000" value="{{ old('amount', $payment?->amount) }}" required></div>@error('amount')<span class="mt-1 block text-xs text-red-600">{{ $message }}</span>@enderror</label>
    <label class="block"><span class="{{ $label }}">Status <b class="text-red-600">*</b></span><select class="{{ $input }}" name="status" required>@foreach(['pending' => 'Menunggu', 'success' => 'Berhasil', 'refunded' => 'Dikembalikan'] as $value => $text)<option value="{{ $value }}" @selected(old('status', $payment?->status ?? 'pending') === $value)>{{ $text }}</option>@endforeach</select>@error('status')<span class="mt-1 block text-xs text-red-600">{{ $message }}</span>@enderror</label>
    <label class="block"><span class="{{ $label }}">Tanggal pembayaran</span><input class="{{ $input }}" type="datetime-local" name="paid_at" value="{{ old('paid_at', $payment?->paid_at?->format('Y-m-d\TH:i')) }}">@error('paid_at')<span class="mt-1 block text-xs text-red-600">{{ $message }}</span>@enderror</label>
    <label class="block sm:col-span-2"><span class="{{ $label }}">Catatan</span><textarea class="mt-2 min-h-28 w-full rounded-xl border border-[#582308]/10 bg-[#faf7f0] px-4 py-3 text-sm outline-none focus:border-[#bd9150]" name="notes" maxlength="2000">{{ old('notes', $payment?->notes) }}</textarea>@error('notes')<span class="mt-1 block text-xs text-red-600">{{ $message }}</span>@enderror</label>
</div>
<div class="mt-8 flex flex-col-reverse gap-3 border-t border-[#582308]/8 pt-6 sm:flex-row sm:justify-end"><a href="{{ $payment ? route('admin.payments.show', $payment) : route('admin.payments.index') }}" class="grid h-11 place-items-center rounded-xl border border-[#582308]/12 px-5 text-sm font-semibold text-[#582308]">Batal</a><button class="h-11 rounded-xl bg-[#582308] px-6 text-sm font-semibold text-white"><i class="fa-solid fa-floppy-disk mr-2"></i>{{ $submitLabel }}</button></div>
